/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections.Generic;
using zFramework.Media;
using static ManManagentUi;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class OutlineInfo
{
  private string _outlineId;
  private string _outlineName;
  private string _parentId;
  private string _level;
  private string _createBy;
  private string _createTime;
  private string _updateBy;
  private string _updateTime;
  private string _remark;
    private List<GetAreaGroupDevs> children = new List<GetAreaGroupDevs>();  //特意加
    private List<NVRInformation> devList = new List<NVRInformation>();  //特意加
    private NVRInformation nvr;
    private int type;

    public NVRInformation NVr
    {
        get
        {
            return nvr;
        }
        set
        {
            __isset.nvr = true;
            this.nvr = value;
        }
    }

    public List<GetAreaGroupDevs> Children
    {
        get
        {
            return children;
        }
        set
        {
            __isset.children = true;
            this.children = value;
        }
    }

    public List<NVRInformation> DevList
    {
        get
        {
            return devList;
        }
        set
        {
            __isset.devList = true;
            this.devList = value;
        }
    }

    public string OutlineId
  {
    get
    {
      return _outlineId;
    }
    set
    {
      __isset.outlineId = true;
      this._outlineId = value;
    }
  }

  public string OutlineName
  {
    get
    {
      return _outlineName;
    }
    set
    {
      __isset.outlineName = true;
      this._outlineName = value;
    }
  }

  public string ParentId
  {
    get
    {
      return _parentId;
    }
    set
    {
      __isset.parentId = true;
      this._parentId = value;
    }
  }

  public string Level
  {
    get
    {
      return _level;
    }
    set
    {
      __isset.level = true;
      this._level = value;
    }
  }

  public string CreateBy
  {
    get
    {
      return _createBy;
    }
    set
    {
      __isset.createBy = true;
      this._createBy = value;
    }
  }

  public string CreateTime
  {
    get
    {
      return _createTime;
    }
    set
    {
      __isset.createTime = true;
      this._createTime = value;
    }
  }

  public string UpdateBy
  {
    get
    {
      return _updateBy;
    }
    set
    {
      __isset.updateBy = true;
      this._updateBy = value;
    }
  }

  public string UpdateTime
  {
    get
    {
      return _updateTime;
    }
    set
    {
      __isset.updateTime = true;
      this._updateTime = value;
    }
  }

  public string Remark
  {
    get
    {
      return _remark;
    }
    set
    {
      __isset.remark = true;
      this._remark = value;
    }
  }

    public int Type
    {
        get
        {
            return type;
        }
        set
        {
            __isset.type = true;
            this.type = value;
        }
    }
    public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool outlineId;
    public bool outlineName;
    public bool parentId;
    public bool level;
    public bool createBy;
    public bool createTime;
    public bool updateBy;
    public bool updateTime;
    public bool remark;
        public bool devList;
        public bool type;
        public bool children;
        public bool nvr;
    }

  public OutlineInfo() {
  }


}

